### ISSUE TITLE
Release for go module support

### ISSUE THREAD

**Issue by spekary** [kenshaw/snaker#1]
Please do a release with an actual release number, like v1.0.0, so that our go modules can point to a version number rather than a commit tag.

**Comment by kenshaw** [comment]
Sorry, must have missed this 2 years ago.  I'd love to know where you're using `snaker` @spekary

**Comment by spekary** [comment]
https://pkg.go.dev/github.com/serenize/snaker will show you that you have close to 300 projects depending on it. Very cool!

I use it in github.com/goradd/goradd, a rapid web-app development project. I am mapping SQL objects and fields to Go language objects, variable names and constants. Some SQL's are not case sensitive, so to delineate words, we use underscores. However, Go is case sensitive, so its nice to convert those to camel case and back.

I additionally need to convert to kebab case at times. Being a web framework, sometimes these objects get pushed to javascript as data attributes, and data attributes are supposed to be named in lower case kebab case. Kebab case would be a nice addition to your library.

As your library handles nicely, sometimes even the most seemingly simple ideas have their intricacies and difficulties.

**Comment by kenshaw** [comment]
@spekary I see. If you want kebab case, just force snake identifier and replace underscores with hyphens. BTW -- I noticed on your project you're using the old package namespace `github.com/knq/snaker`.  I'd suggest updating to `github.com/kenshaw/snaker`.

**Comment by spekary** [comment]
Will do.
